language: node_js
sudo: false
install: true
branches:
  only:
      - master

script:
    - openssl aes-256-cbc -K $encrypted_412afa050e5f_key -iv $encrypted_412afa050e5f_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    - ssh -o "StrictHostKeyChecking no" ansible@194.87.146.232 'ansible-playbook /etc/ansible/playbooks/rent-frontend.yml'